// AUTO-GENERATED by this package's scripts/generate-assets.mjs — do not edit.
// Source: openstack-uicore-foundation/lib/css/components/free-text-search.css
import type { VendorSheet } from '../../core/vendor-sheet';

export const sheet: VendorSheet = {
  id: "uicore-free-text-search",
  css: ".extra-question-error{color:red;display:block;font-size:12px;font-weight:700;margin:auto 0;padding:0}.extra-question-error:before{content:\"\\f071\";font-family:FontAwesome;padding-right:5px}.question-label-container a{text-decoration:underline!important}.questions-form{padding-bottom:5em}.questions-form h4{font-size:12pt}.questions-form .abc-checkbox{padding:0!important}.questions-form .form-check-label{font-weight:400!important}.questions-form .abc-radio label{max-width:90%}.questions-form form>div.checkbox-wrapper{align-items:start;display:grid;gap:15px;grid-template-columns:0fr 14fr;grid-template-rows:1fr}.questions-form form>div.checkbox-wrapper .input-wrapper,.questions-form form>div.checkbox-wrapper .input-wrapper .form-check{width:35px}.questions-form form>div.checkbox-wrapper .checkbox-mandatory{color:red;position:absolute}.questions-form form>div.checkbox-wrapper .eq-checkbox-label{padding-top:0}\n/*# sourceMappingURL=free-text-search.css.map*/",
  fontFaces: "",
};
