// AUTO-GENERATED by packages/widgets/scripts/generate-assets.mjs — do not edit.
// Source: openstack-uicore-foundation/lib/css/components/circle-button.css
import type { VendorSheet } from '@openeventkit/widget-core/vendor-sheet';

export const sheet: VendorSheet = {
  id: "uicore-circle-button",
  css: ".pTjbvR2PI3JIAfGGYR5C{border-color:transparent;border-radius:20px;bottom:0;color:#fff;font-size:20px;height:30px;padding:0;position:absolute;right:0;text-align:center;width:30px}.pTjbvR2PI3JIAfGGYR5C.BnU6_vcWc8sasL8roBPA{background-color:#e39900}.pTjbvR2PI3JIAfGGYR5C.yREg1belHCLDAYYfAg77{background-color:#7ed321}.pTjbvR2PI3JIAfGGYR5C.mFp_9X3SzjgPNXRSXiFR{background-color:#396bd0}.pTjbvR2PI3JIAfGGYR5C i{margin-top:4px}",
  fontFaces: "",
};
